### ISSUE TITLE
Add new analysis - CO2 Emissions

### ISSUE THREAD

**Issue by informationvulture** [dani0105/free-datasets#3]
## Description
Using R, I will analyse the CO2 emissions using the `CO2-emissions/CN_CHINA.csv` dataset.

## Details
I will provide various types of visual analysis (histograms, charts, etc.) on the data, as-well details on outliers and possible future predictions.

## Languages/Libraries
This will be done using only R and will use the existing dataset, not moving/copying it again. I suspect several R libraries will be needed. I will provide both the R script and images in a separate folder to be included in the `README`.

**Comment by dani0105** [comment]
go ahead
